<?php

$path = "'" . getcwd()."\DataFolder\data_alarm.csv" . "'";

require "db_initialize.php";

$query = "
COPY(
  SELECT
  alarms.alarmid, 
  alarms.nodeid, 
  alarms.ipaddr, 
  alarms.alarmtype, 
  alarms.counter, 
  alarms.severity, 
  alarms.lasteventtime, 
  alarms.firsteventtime, 
  alarms.description, 
  alarms.logmsg, 
  node.dpname, 
  node.nodetype, 
  node.nodesysoid, 
  node.nodesysname, 
  node.nodesysdescription, 
  node.nodesyslocation, 
  node.nodesyscontact, 
  node.nodelabel
  FROM 
  public.alarms, 
  public.node
  WHERE 
  node.nodeid = alarms.nodeid) 
TO $path With CSV HEADER;
";
$result = pg_query($query) or die('Query failed: ' . pg_last_error());

if(file_exists("DataFolder\data_alarm.csv")){

  $myfile = fopen("DataFolder\data_alarm.csv", "a+") or die("Unable to open file!");
  fwrite($myfile, "System time: ". date('Y-m-d H:i:s')."\n");
  fwrite($myfile, "These data are generated by Electroline Vanguard-HE NMS Portal"."\n");
  fwrite($myfile, "2015 Electroline Equipment Inc. All rights reserved."."\n");
  fclose($myfile);
  file_downloading();


}




function file_downloading($file="DataFolder\data_alarm.csv"){
  if(file_exists($file)) {
    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename='.basename($file));
    header('Content-Transfer-Encoding: binary');
    header('Expires: 0');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Pragma: public');
    header('Content-Length: ' . filesize($file));
    ob_clean();
    flush();
    readfile($file);
    exit;
  }
}



?>