<?php

$path = "'" . getcwd()."\DataFolder\data_inv.csv" . "'";

$dbpath = $_SERVER["DOCUMENT_ROOT"] . "/vanguardhe/daemon_scr/daemon_db_init.php";
require_once($dbpath);  // to initialize snmp 

$query = "
COPY(
  SELECT 
  daemondevice.id, 
  daemondevice.time, 
  daemondevice.ip, 
  daemondevice.status, 
  daemondevice.description, 
  daemondevice.mib, 
  daemondevice.uptime, 
  daemondevice.contact, 
  daemondevice.name, 
  daemondevice.location, 
  daemondevice.service, 
  daemondevice.latitude, 
  daemondevice.longtitude, 
  daemondevice.mac, 
  daemondevice.sn, 
  daemondevice.provision
FROM 
  public.daemondevice) 
TO $path With CSV HEADER;
";
$result = pg_query($query) or die('Query failed: ' . pg_last_error());

if(file_exists("DataFolder\data_inv.csv")){
  
  $myfile = fopen("DataFolder\data_inv.csv", "a+") or die("Unable to open file!");
  fwrite($myfile, "System time: ". date('Y-m-d H:i:s')."\n");
  fwrite($myfile, "These data are generated by Electroline Vanguard HE System"."\n");
  fwrite($myfile, "2015 Electroline Equipment Inc. All rights reserved."."\n");
  fclose($myfile);
  file_downloading();


}

function file_downloading($file="DataFolder\data_inv.csv"){
  if(file_exists($file)) {
    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename='.basename($file));
    header('Content-Transfer-Encoding: binary');
    header('Expires: 0');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Pragma: public');
    header('Content-Length: ' . filesize($file));
    ob_clean();
    flush();
    readfile($file);
    exit;
  }
}



?>